### ISSUE TITLE
Create a mozillians.org group for Reps

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#29] opened 2016-05-12 13:10 UTC
## Goal:

Create a mozillians group to list all Reps.
In that way we can sync Discourse and Reps to get all them subscribed to the group for all the notifications and close the mailing list like said on #272.
## Roles:

Responsible: @nukeador
Accountable: @nukeador
Supporting: @ppapadeas 
Consulted: Council
Informed: Reps, mentors
## Required:
- [ ] Email to reps to update Mozillians.org profile with info and emails (@ppapadeas)
- [x] Create a new group in Mozillians.org named Reps
- [x] Populate it with proper legal information and make it closed
- [ ] Inform mentors about this change 
- [ ] Make all current mentors curators of the group "Reps"
- [ ] Change the SOP to include invitation for this group and removing signing of legal document

**Comment by nukeador** [comment] 2016-05-12 16:52
Group is created, waiting for @ppapadeas comms to start adding mentors as curators

https://mozillians.org/group/reps/

**Comment by nukeador** [comment] 2016-05-25 10:31
Waiting for @ppapadeas  email to all reps

**Comment by nukeador** [comment] 2016-06-02 04:55
Ping @ppapadeas

**Comment by nukeador** [comment] 2016-06-02 04:55
Ping @ppapadeas

**Comment by ppapadeas** [comment] 2016-06-02 12:13
Hey @nukeador . We need to coordinate the email. First draft here:
https://public.etherpad-mozilla.org/p/reps-mozillians-email

Please review so we can send.

**Comment by hmitsch** [comment] 2016-06-02 12:24
Nice email. If I may suggest:
Maybe you could add a <tl;dr> to the top, clearly pointing out the call to action with the 2 week deadline. 

-Henrik

-- 
Henrik Mitsch

**Comment by ppapadeas** [comment] 2016-06-02 13:10
Done!

**Comment by nukeador** [comment] 2016-06-02 14:29
I've added somethings and a suggestion to also explain the upcoming group invitation

**Comment by nukeador** [comment] 2016-06-07 10:24
@ppapadeas do you need anything else here before sending the comms?

**Comment by nukeador** [comment] 2016-06-20 11:26
@ppapadeas As commented in London, this is ready for you to send the email.

**Comment by nukeador** [comment] 2016-07-08 10:55
@ppapadeas Please, we need an answer here. Thanks.

**Comment by nukeador** [comment] 2016-07-15 16:06
Apparently this is not happening at the moment due bandwidth issues.

**Comment by nukeador** [comment] 2016-09-29 13:20
@ppapadeas @hmitsch has this been considered for your team roadmap at some point?

**Comment by ioana-chiorean** [comment] 2016-11-15 09:53
@nukeador did we change anything here?

**Comment by hmitsch** [comment] 2016-11-15 10:08
> @ppapadeas @hmitsch has this been considered for your team roadmap at some point?

What roadmap are we talking about?
The email sounds as if functionality had been built already. If it is not built yet, it is definitely not on our roadmap for the time being.

@ppapadeas can you please clarify the current situation?

**Comment by nukeador** [comment] 2016-12-29 11:42
@hmitsch This was the integration of Reps portal with mozillians so we just have to manage the group from mozillians and also allowing us to easily sign the Reps agreement and have regular commitment renewals. This is something we are going to need sooner than later, is it on your roadmap? (this has been "on hold" more than 7 months now)

**Comment by hmitsch** [comment] 2017-01-09 16:43
Aligning on priority with @nukeador. Mail sent.

**Comment by nukeador** [comment] 2017-08-21 11:24
@hmitsch are we tracking this elsewhere?

**Comment by Mte90** [comment] 2018-01-05 22:12
Any updates for this one?

**Comment by hmitsch** [comment] 2018-01-05 22:19
@Mte90 what `this` are you referring to? 😄 

Is about https://github.com/mozilla/Reps/issues/29#issuecomment-269618783 ?
We are currently not planning to transition the Reps Portal roles concept to integrate Mozilla IAM capabilities. Is this what you are asking for?

-Henrik

**Comment by Mte90** [comment] 2018-01-05 22:24
Actually the object, create and populate the reps group on mozillians with reps.
In that way we can move on evaluating more integration with AIM in the future like for discourse.

**Comment by hmitsch** [comment] 2018-01-05 22:37
@Mte90 thanks for the clarification.

In this case I am fully on board:
* Discourse is a first-class IAM citizen. We would be excited to use a Mozillians group (e.g. https://mozillians.org/group/reps/) as the access management mechanism for a restricted Reps category

I don't know who owns the task to make sure all Reps are added to the Reps group. I'd say it should fall on the Curators (ping @nukeador @couci).

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/869692/34631604-6d6d85b6-f271-11e7-901b-b0f353b153de.png">


-Henrik

**Comment by Mte90** [comment] 2018-01-16 13:01
Few updates after some discussion:

* Mozillians need to be the center to manage all the users so *actually* the Reps portal with a duplicate of the profile is wrong. The right way is to manage the reps from mozillians.org.
When a reps is alumni need to be removed on mozillians and when there is a new one need to be updated on the portal.
* We need to add them manually

**Comment by Mte90** [comment] 2018-06-14 16:33
It is blocking also newsletter stuff, just as a note.

**Comment by Timmaks** [comment] 2020-05-14 19:04
do we need this issue still open?

**Closed** 2020-05-14 19:36 UTC
Labels: Communications, any other business
