### ISSUE TITLE
Short video from reps applicant

### ISSUE THREAD

**Issue by Faisalaziz** [mozilla/Reps#229] opened 2017-07-27 05:04 UTC
Hi Council/Peers,

I was thinking if we can make mandatory for reps applicant to post a short video explaining why they want to become a rep? Just like council candidates applicant will explain his goals , track and reason why he is applying for program. This would help in screening moreover if we make it public it will help in better outreach. Looking forward for your suggestions.

**Comment by MichaelKohler** [comment] 2017-07-27 09:28
Hi Faisal

Thanks for filing an issue for this idea. I would like to keep this here as a tracking bug and start a discussion around this on Discourse. Would you mind posting this idea to the Discourse thread so we can discuss it more broadly?

https://discourse.mozilla-community.org/t/reps-application-criteria-updated/17387

Thanks again,
Michael

**Comment by Faisalaziz** [comment] 2017-08-02 06:23
Thanks @MichaelKohler , I'll post it tonight.

**Comment by Mte90** [comment] 2017-09-29 10:33
Any updates for this one?
We can define a new onboarding criteria for this one and discuss.

**Comment by Mte90** [comment] 2017-10-02 09:16
I added that on reps council notes to discuss about it :-)
Probably we need a format (maybe the applicant can use the on boarding criteria as guidelines for the video)

**Comment by Mte90** [comment] 2017-11-02 10:43
Actually we not find the time and interest to work on that without more example about the benefit of that.

Actually all the information that we require are usually written on the ticket where we can ask more. This speed up the review and avoiding to see a video to find what we care for the application.

**Comment by Mte90** [comment] 2017-11-20 09:54
As I written actually we want to improve more the onboarding with new criteria and the video will be only a complication because often the criteria are not included in the ticket itself and will be only a duplicate of information that maybe doesn't fir on our request (that will be added later on the ticket itself).

**Closed as completed by Mte90** 2017-11-20 09:54 UTC
Labels: Onboarding
