### ISSUE TITLE
Budgeting - Document where others are going instead of Bugzilla form so we can choose best option

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#205] opened 2017-06-28 16:43 UTC
## Goal: 
We have alternative for budget & swag management instead of Bugzilla.

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible: @couci @kelimuttu

Accountable: @kelimuttu

Supporting:@couci, Reps Council

Consulted: Reps Council

Informed: CD Team

## Required: 
- [ ] List of alternatives has been proposed

**Comment by kelimuttu** [comment] 2017-07-12 04:51
Just found [this](https://github.com/Kickball/awesome-selfhosted#money-budgeting-and-management).Haven't explore all of them, but can be a good reference. Tho' most of them will require technical maintenance (don't know if that will be possible).

**Comment by Mte90** [comment] 2017-07-12 09:48
I suggest during all hands: http://limesurvey.org/

I think that to find what is the best alternative is better to define a list about what we need because maybe for us is enough a ticket system very powerful or only a survey.

**Comment by MichaelKohler** [comment] 2017-07-18 06:00
@kelimuttu @couci could one of you edit the initial description to include the goals, responsible persons, and tasks?

**Comment by kelimuttu** [comment] 2017-08-30 12:51
@MichaelKohler Done. 

Also, George share [this link](https://opencollective.com/learn-more) today. Seems like a potential alternative, although the project is still on development right now.

**Comment by MichaelKohler** [comment] 2017-08-30 12:54
> Also, George share this link today. Seems like a potential alternative, although the project is still on development right now.

I like it as it's transparent by design. However, I'm not sure how transparent our finances actually *can* be from a legal/finance perspective.

**Comment by kelimuttu** [comment] 2017-08-30 15:18
Yeah. We need to explore the project once it's set up. I hope we'll be able to tweak it.

**Comment by couci** [comment] 2018-01-17 17:24
@kelimuttu is working on this holistically. @kelimuttu once your report is out of the raft face we should share.
Closing this one

**Closed as completed by couci** 2018-01-17 17:24 UTC
Labels: Resources
