### ISSUE TITLE
Council elections

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#15] opened 2016-04-17 11:02 UTC
## Goal: 
* Hold the council election in order to occupy the spots that are free after the term of one year is ending for Michael Kohler, Christos Bacharakis, Shahid Farooqui.

## Success:
* The elections take place and we have 3 new council members

## Roles:
Owner: @ioana-chiorean 
Involved: @brianking @nukeador

## Required: 
- [x] Prepare the timeline and the steps (@ioana-chiorean, Due: Aug 20th) 
- [x] Send out the announcement (@ioana-chiorean, Due: Aug 25th) 
- [x] Start gathering nominations (@ioana-chiorean, Due: Aug 25th) 
- [x] Close nominations (@ioana-chiorean, Due: Aug 31st) 
- [x] Prepare Q&A (@ioana-chiorean, Due: Aug 31st) 
- [x] Run Q&A (@ioana-chiorean, Due: Sep 1st) 
- [x] Start Voting (@ioana-chiorean, Due: Sep 7th) 
- [x] Close voting and announce results.  (@ioana-chiorean, Due:  Sep 11th)

**Comment by nukeador** [comment] 2016-06-03 12:44
@ppapadeas we need an update here. Specially about comms to Reps about the change in dates, thanks :)

**Comment by hmitsch** [comment] 2016-06-04 06:56
Reps are asking for transparency on the election process: https://discourse.mozilla-community.org/t/council-elections/9077

**Comment by hmitsch** [comment] 2016-06-16 09:53
Reminder to self (@hmitsch): The *milestone* is August, that's why it will be in August.

**Comment by ioana-chiorean** [comment] 2016-06-16 10:18
Added details to the description and some of the steps already identified. 🎉

**Comment by ioana-chiorean** [comment] 2016-06-16 10:19
> Reminder to self (@hmitsch): The milestone is August, that's why it will be in August. 

@hmitsch -> I would say till August to be done ( The updated timeline above is for July )

**Comment by ioana-chiorean** [comment] 2016-07-20 22:23
Hi all - just a quick update here. 
The peers body spent the last few week investigating different approaches for having the council elections. due to time constraints we will proceed with the know process and we will start after to prepare the new process to be in place for the next elections. 
We will follow-up on this one. 

##New Timeline proposed (All times in 09:00 UTC)
- [ ] July 21st - call for candidates (eligible Mozilla Reps Mentors only)
- [ ] July 31st - call closes 
- [ ] Aug 1st - start of campaign period
-- candidates are given 7 days to answer questions and post them on their profile page
-- candidates are given 7 days to publish a 30-120 seconds campaign video
- [ ] Aug 5th deadline for answers and videos to be published
-- Reps are encouraged to read through candidate replies and watch
    their videos during the week
- [ ] Aug 8th - voting starts 
- [ ] Aug 11th - voting ends - new elected members are announced and 
- [ ] Aug 15th - the Council Onboarding begins

Previous texts helpers:
Hello all,

== Intro to Elections ==
The Mozilla Reps program has been a volunteer driven program since day
1. In that spirit the core governing body of the program, the Council,
was designed to be an elected body with new members chosen by all Reps
every six months.
_* reps Next notes_

More background about the history of the Council and its structure can
be found here [1] and here [2] and you can find a visualization of the
composition here [3]

The time has come for a new round of elections and this time 3
positions need to be filled. ____ , _____ re reaching the end
of their 12-month terms and their seats need to be replaced for
another 12-month term.

Nominations are open as of today for Mozilla Reps mentors that are
eligible (see criteria here [3])

This is an exciting time for the Reps program and our role as Reps to
help Mozilla build a better web has never been as critical. Thank you
all for being part of this!

On behalf of Mozilla Reps Peers and Council,

**Comment by MichaelKohler** [comment] 2016-07-23 19:46
Sounds great to me, good work!

**Comment by hmitsch** [comment] 2016-07-23 21:16
Fully agree with proposed approach and timeline. 
Unfortunately we already missed milestone 1, however I would NOT adapt the following milestones. Let's get moving. 
Onwards and thanks to @ioana-chiorean for driving this.

**Comment by Timmaks** [comment] 2016-07-23 21:42
One thing on the time line, in a lot of country's  (i think) it is summerbreak time.. for me for example it would be impossible to keep this timeline because i am on vacation with my family. But i wouldn't be a candidate so this is not a issue for me ;-)

**Comment by brianking** [comment] 2016-07-25 21:51
Good flag Tim, it might also be an impediment to voting for some Reps.

**Comment by ioana-chiorean** [comment] 2016-08-11 22:06
**New New Timeline proposed** (All times in 09:00 UTC)

- [ ] Aug 12/13 - call for candidates (eligible Mozilla Reps Mentors/Cohort only)
- [ ] Aug 19 - call closes 
- [ ] Aug 20- start of campaign period
-- candidates are given 5 days to answer questions and post them on their profile page
-- candidates are given 5 days to publish a 30-120 seconds campaign video
- [ ] Aug 24th deadline for answers and videos to be published
-- Reps are encouraged to read through candidate replies and watch
    their videos during the week
- [ ] Aug 25th - voting starts 
- [ ] Aug 30th - voting ends - new elected members are announced and 
- [ ] Sep 1 st - the Council Onboarding begins

I shorten the time to prepare the campaign as the people that will candidate will be engaged so normally they should be available for this in the 5 days time. 

Please raise any flags ASAP to be able to start is shortly.

**Comment by hmitsch** [comment] 2016-08-11 23:02
The 5 days of voting at the end of August might still fall into the typical "European vacation time". However, if we announce the elections by mid-August, there are two weeks to get into the right mind-set for the elections.

For me the time line is tight but manageable. +1 from my side!

**Comment by MichaelKohler** [comment] 2016-08-11 23:14
Given that we're already almost 2 weeks behind schedule, I think a tighter schedule makes sense.

**Comment by rosanardila** [comment] 2016-08-12 08:37
+1 from my side for the time line

**Comment by couci** [comment] 2016-08-12 10:04
+1 for me too, should we say specifically that cohort candidates are eligible for only one position?

**Comment by comzeradd** [comment] 2016-08-12 12:05
Looks good to me too :+1:

**Comment by ioana-chiorean** [comment] 2016-08-18 14:33
**New New Timeline proposed** (All times in 09:00 UTC)

- [ ] Aug 18 - call for candidates (eligible Mozilla Reps Mentors/Cohort only)
- [ ] Aug 24 - call closes 
- [ ] Aug 25- start of campaign period
-- candidates are given 5 days to answer questions and post them on their profile page
-- candidates are given 5 days to publish a 30-120 seconds campaign video
- [ ] Aug 29th deadline for answers and videos to be published
-- Reps are encouraged to read through candidate replies and watch
    their videos during the week
- [ ] Aug 30th - voting starts 
- [ ] Sep 4th - voting ends - new elected members are announced and 
- [ ] Sep 5 st - the Council Onboarding begins

I shorten the time to prepare the campaign as the people that will candidate will be engaged so normally they should be available for this in the 5 days time. 

Please raise any flags ASAP to be able to start is shortly.

**Comment by ioana-chiorean** [comment] 2016-08-22 22:11
Mail to be sent out any change I might have miss? Or wording to improve?

_ Hello all,

== Intro to Elections ==

The Mozilla Reps program has been a volunteer driven program from the beginning. As Pierros previously said In that spirit the core governing body of the program, the Council, was designed to be an elected body with new members chosen by all Reps every six months. More background about the history of the Council and its structure can be found here [1] and here [2] .

== Available positions ==
The time has come for a new round of elections and this time 4 positions need to be filled.
Michael Kohler, Christos Bacharakis and Shahid Farooqui are reaching the end of their 12-month terms and their seats need to be replaced for another 12-month term.
Arturo Martinez’s term is also ending after more than 6 months due to personal availability.

== Nominations are open ==
As Rosana mentioned in her mail about the Changes in Reps Program management and Council mail, nominations are open as of today as follows:
- 3 positions up for Mozilla Reps mentors that are
eligible (see criteria here [3])
- 1 position up for all Reps that are part of the Participation Cohort ( but not necessary a  Reps mentor) with a term of 6 months.

== Next steps and timeline ==
Add yourself to the etherpad -https://public.etherpad-mozilla.org/p/remo-elections-aug-2016  and when the call closes stay close to the announcements ( be available online to receive mails)

- Aug 23 - call for candidates (eligible Mozilla Reps Mentors/Cohort only)
- Aug 29 - call closes
- Aug 30- start of campaign period -- candidates are given 5 days to answer questions and post them on their profile page -- candidates are given 5 days to publish a 30-120 seconds campaign video
- Sep 4 - deadline for answers and videos to be published — Reps are encouraged to read through candidate replies and watch their videos during the week
- Sep 5 - voting starts
- Sep 9 - voting ends - new elected members are announced and
- Sep 10 - the Council Onboarding begins

This is an exciting time for the Reps program and our role as Reps to help Mozilla build a better web has never been as critical. Thank you all for being part of this!

On behalf of Mozilla Reps Peers and Council,
Ioana

[1] https://wiki.mozilla.org/ReMo/Council
[2] https://wiki.mozilla.org/ReMo/Council/History
[3] https://wiki.mozilla.org/ReMo/Council/Elections#Candidates_

**Comment by MichaelKohler** [comment] 2016-08-22 22:23
This sounds great! I have a two minor nits though:

* the link [3] should be without the _ at the end to make sure it jumps to the right section of the page
* didn't notice before: "to answer questions and post them on their profile page" -> aren't we gonna do Discourse again as last time?

Thanks for your great work so far, let's do this 👍

**Comment by brianking** [comment] 2016-08-23 09:03
For Arturo:
"personal availability" might read better as "lack of personal availability" or "personal unavailability"

**Comment by ioana-chiorean** [comment] 2016-08-23 12:02
@MichaelKohler 

> the link [3] should be without the _ at the end to make sure it jumps to the right section of the page

I see it without - it was present in initial phase from the italic syntax 

> aren't we gonna do Discourse again as last time?

yes, we are. 

@brianking - good suggestion

Thank you!

**Comment by hmitsch** [comment] 2016-08-23 23:51
In true Henrik-fashion, I'd add a <tl;dr> to the top.

> 
> == TL;DR ==
> 
> Unfortunately there is no short-cut this time. If you consider yourself an active Mozilla Rep, please read the full email, reflect on its contents and take action.

**Comment by ioana-chiorean** [comment] 2016-08-25 11:43
I took me longer than expected. Sorry. 😞 
https://discourse.mozilla-community.org/t/important-council-elections-please-read/10491

**Comment by rosanardila** [comment] 2016-08-25 11:53
thanks so much Ioana! Should we send it to reps-general too?

**Comment by ioana-chiorean** [comment] 2016-08-25 12:46
I did mail it as first step ( same text but wanted to have a discourse thread link for the mail) @rosanardila  and @nukeador just pinned it to the Telegram group too.

**Comment by hmitsch** [comment] 2016-08-25 20:44
Concerning comment https://github.com/mozilla/Reps/issues/15#issuecomment-242357855 ... please do NOT apologize, dear Ms. Module Owner. You are doing an **awesome** job here. Keep it up and thank you so much for not letting us down.

**Comment by ioana-chiorean** [comment] 2016-08-31 12:33
Nominations are now closed! We have the following applicants:

1 Spot Reps Cohort :
- [Daniele Scasciafratte](https://reps.mozilla.org/u/Mte90/)
- [Elio Qoshi](https://reps.mozilla.org/u/elio)
- [Mijanur Rahman Rayhan]( https://reps.mozilla.org/u/mijanur/)
- [Flore Allemandou](https://reps.mozilla.org/u/Flore/)

3 Spots from Mentors:
- [Mohammed migdadi](https://reps.mozilla.org/u/Mohammed_Migdadi/)
- [Adriano Cupello](https://reps.mozilla.org/u/dricupello)
- [Alex Lakatos](https://reps.mozilla.org/u/alex_lakatos/)
- [Michael Kohler](https://reps.mozilla.org/u/michaelkohler/)
- [Anup Kumar Mishra](https://reps.mozilla.org/u/anupkumarmishra29/)
- [Hossain Al Ikram](https://reps.mozilla.org/u/hossainalikram/)

**Comment by comzeradd** [comment] 2016-09-01 09:30
Nice turnout. I like the fact we have so many nominations :rocket:

**Comment by shahidfarooqui** [comment] 2016-09-05 17:24
Glad to see such a huge turn-up (nomination) including Michael stepping again to another round of wonderful job :)

**Comment by ioana-chiorean** [comment] 2016-09-06 09:52
Tasks to prepare:

1 Spot Reps Cohort :
- Daniele Scasciafratte
 - [ ] video
 - [ ] replies on discourse questions
- Elio Qoshi
 - [ ] video
 - [ ] replies on discourse questions
- Mijanur Rahman Rayhan
 - [ ] video
 - [ ] replies on discourse questions
- Flore Allemandou
 - [ ] video
 - [ ] replies on discourse questions

3 Spots from Mentors:
- Mohammed migdadi
 - [ ] video
 - [ ] replies on discourse questions
- Adriano Cupello
 - [ ] video
 - [ ] replies on discourse questions
- Alex Lakatos
 - [ ] video
 - [ ] replies on discourse questions
- Michael Kohler
 - [ ] video
 - [ ] replies on discourse questions
- Anup Kumar Mishra
 - [ ] video
 - [ ] replies on discourse questions
- Hossain Al Ikram
 - [ ] video
 - [ ] replies on discourse questions

**Comment by ioana-chiorean** [comment] 2016-09-11 13:05
Results:

- [1 Spot Council](https://reps.mozilla.org/v/reps-council-elections-september-2016-1-spot-reps-cohort/) from Cohort

**1.  Flore Allemandou - 394** 
-------------------------------
2. Elio Qoshi -374
3. Daniele Scasciafratte - 354
4. Mijanur Rahman Rayhan - 275

-  [3 Spots in Council](https://reps.mozilla.org/v/reps-council-elections-september-2016-3-spots-from-mentors/) from Mentors

**1. Michael Kohler - 685
2. Alex Lakatos - 512
3. Adriano Cupello - 471**
-------------------------------
4. Mohammed Migdadi - 440
5. Anup Kumar Mishra - 422
6. Hossain Al Ikram - 421

**Comment by ioana-chiorean** [comment] 2016-09-12 10:43
Mails sent with the results!

**Closed by ioana-chiorean** 2016-09-12 10:43 UTC
Labels: in progress, Leadership, P1
