### ISSUE TITLE
Mid-term planning for Indonesia decided

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#5] opened 2016-04-17 10:16 UTC
## Goal: 
To have a solid decision for Indonesian mid-term planning budget.

## Success:
Council gave a final decision for the Indonesian mid-term budget planning. 

## Related Issues & Links: 
- [Midterm Budget Indonesia (spreadsheet)](https://docs.google.com/spreadsheets/d/1LPZpL48v_um6P_1DMqJS6KeC4U_5Fe8JAZaKS1uzHwQ/edit?usp=gmail#gid=1772027292)
- [Budget Template Guidelines](https://docs.google.com/document/d/1GhxruLeg8DjAge-fB4fR5Q3hDgTpEnGEA38tiUhY1jM/edit#heading=h.noaigsuo7irs)
- [Midterm Budget Plan Guidelines](https://docs.google.com/document/d/1hpDVJTEGRAeJTeE3hJaH702QxOpk0vA6-kBrZQnYSm0/edit?usp=sharing)

## Roles:
Owner: @rara79 @couci 
Involved: @alamanda @andi-belutz

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by nukeador** [comment] 2016-04-27 16:37
@rara79 please update the details in this issue. Thanks!

**Comment by rara79** [comment] 2016-04-29 18:22
Based on the previous Reps Council call, action items are:

- Create an update proposal based on the current spreadsheet
- Create a call with the council, Indonesian team (MozID's finance role Andi Darmawan and Dian Ina), and Konstantina

**Comment by nukeador** [comment] 2016-05-06 20:33
Can you please update this one with next steps? Thanks!

**Comment by brianking** [comment] 2016-05-07 18:41
Late next week when I am in Jakarta I will work with @alamanda and @rara79 on an updated slide deck proposal.

**Comment by rara79** [comment] 2016-05-11 16:31
Next steps still the same as I commented above :)

**Comment by MichaelKohler** [comment] 2016-05-18 17:49
@rara79 @brianking could you two work on it while Brian was in Jakarta?

**Comment by MichaelKohler** [comment] 2016-06-17 13:23
![photo171905228960016895](https://cloud.githubusercontent.com/assets/330324/16151890/7194106a-349f-11e6-93c0-0d67cf032949.jpg)

**Comment by rara79** [comment] 2016-06-17 15:13
We had meeting with @brianking on May 14th at Jakarta, and here's what we did:
- discussion and listening to the community's frustration
- hacking on the previous slides: https://docs.google.com/presentation/d/1X8xMplxiQ9livT6wqO3MKK-xNtA6KXeBe0K02RjHJyY/edit#slide=id.gc6f8954bc_0_116
- hacking on the spreadsheet: https://docs.google.com/spreadsheets/d/1LPZpL48v_um6P_1DMqJS6KeC4U_5Fe8JAZaKS1uzHwQ/edit#gid=1772027292

May 25th, @brianking mentioned that it looks like some more changes are going to be needed. However, some of them might be just 'branding' changes, while others will be exploring activities more aligned with current participation focus, e.g. campus, innovation, and so on.

At the council meeting, June 1st:
- Document is ready to be review again
- Setting up a call for @rosanardila @couci and the Indonesian Reps, before London All Hands 2016

**Comment by rara79** [comment] 2016-06-17 15:19
June 18th, a 30-mins call between @rosanardila @couci and the Indonesian Reps already happened. Meeting notes: https://public.etherpad-mozilla.org/p/RepsIDRosanaKonstantina
Suggestions: 
- Break down on the areas you want to work
- Work on a 3 month plan

**Comment by alamanda** [comment] 2016-06-24 08:13
@rara79 the call with @rosanardila and @couci happened on June 8th instead of June18th.

**Comment by alamanda** [comment] 2016-06-24 08:25
I read here that @rara79 has been sending updates from the Indonesian community side. I wonder if the council members have read all the updates we made thoroughly to have better understanding about the midterm planning? 

I am aware that there's a council meeting regarding this matter during All Hands. Would any council member kindly give us (@andi-belutz and I) updates regarding the meeting and its result? When will we be invited to a council meeting to answers questions (if the council members still have any) and describe the planning (if the council members still not understand it thoroughly)?

We're looking forward to read more and see more action from the council side on this matter.

**Comment by alamanda** [comment] 2016-06-29 14:03
as per @MichaelKohler request, I copied the important links for Indonesian community midterm planning once again: 
1. http://bit.ly/1YrwEr0 (Budget Spreadsheet)
2. http://bit.ly/29ePbFI (Community Roadmap Slides)

For the record, I noticed here that these links are listed here in Related Issues and Links on top part of this github issue and @rara79 has explained that those spreadsheet and slides have been updated.

**Comment by rara79** [comment] 2016-06-29 17:06
From council meeting on June 29th:

- ICYMI, 
    - community roadmap slides https://docs.google.com/presentation/d/1X8xMplxiQ9livT6wqO3MKK-xNtA6KXeBe0K02RjHJyY/edit#slide=id.gd4b047a73_0_65
    - Budget spreadsheet https://docs.google.com/spreadsheets/d/1LPZpL48v_um6P_1DMqJS6KeC4U_5Fe8JAZaKS1uzHwQ/edit#gid=1772027292
- From the last council meeting in London, there’s no clear decision yet because the discussion was interrupted
- [Action Item] inviting @couci, @alamanda and @andi-belutz to the next council meeting to present and discuss more about the planning and budget (on July 13th, since July 6th is Eid Fitr day - celebration the end of Ramadan)
- [Action Item] @MichaelKohler to send the invitation to @couci @alamanda @andi-belutz for July 13th council meting
- Rosana's suggestion: every initiative on their own, while using the current planning as a community planning tool, but not towards Reps Council

**Comment by rara79** [comment] 2016-07-21 01:05
@alamanda and @andi-belutz from the Indonesian community was invited to the council meeting to talk about the Indonesian mid-term planning they are working on to decide on next steps. @couci also there to give different perspective.

- Master goal: half of the community left after the community conflict last year, the Indonesian community want to get new people, in new locations and strengthen their core in the existing local communities.
- Budgeting is easier when done for multiple events - and outside sponsorship is hard when not planned a few months ahead
- @nukeador : what can Council help out with? @alamanda : approve the budget
- Lack of constructive feedback from Council
- @rosanardila suggestion: decouple the plan from the events, so we can have “a month of swag” and the Indonesian Community can start experimenting, using the plan as guidance
     - We are agreeing that local production should be supporting
     - @alamanda and @andi-belutz diasgree to take out the swag plan without knowing whether the event plan will be approved or not.
     - @couci : swags are only for supporting the events
- @andi-belutz : midterm planning was made to help Mozilla Indonesia becomes a self-sustaining community. 
- @rosanardila and @nukeador :  the approved plan must match with Mozilla's priority, and the problem is Mozilla keeps changing priority and we don't know what will happen in the next 6 months.
- the conversation went too long and the time is already up. We need to setup a separate call apart from the council meeting schedule. 

[Action Item] Arrange a separate call to talk about the midterm planning.

**Comment by hmitsch** [comment] 2016-08-20 10:02
@hmitsch reminder to self: look at this from an "agile coach" perspective. :-)

**Comment by alamanda** [comment] 2016-08-21 03:15
our committed partner in Medan, where we supposed to do various community building activities in August, moved to other city. we need to re-start from scratch and find another local partner/supporter if we want to build community in this city. all the hard work we've been doing to get local partners initially, wasted. all those time spent, time that we can never get back, lost forever. 

other partners/supporters have stopped asking about Mozilla Indonesia's plans and activities in their area due to the long process. I think we have lost our credibility as well. the credibility we built within our networks with personal guarantee

**Comment by nukeador** [comment] 2016-09-01 19:50
We hold a meeting with the Indonesian community last week.

Notes: https://docs.google.com/document/d/1y2YuxD6azkgxCRobpSfx4iogiBqOQ_Vp_FOq7i2wjG4/edit#

Indonesian community will contact the council as soon as they have discussed internally to see how Council can guide on aligning with current focus initiatives at Mozilla.

Since we clarified on the no-need for approval from Council on the mid-term plan, I'm closing this.

**Closed** 2016-09-01 19:50 UTC
Labels: blocked, in progress, P2, Regional
